Traceback (most recent call last):
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 644, in _map
    if rank == 0:
AssertionError: _map: indices and values have different length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchTillage.py", line 8, in <module>
    results_dir = mainTillage.XcGrowth(25.5, 30.,0,spellData )
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/mainTillage.py", line 106, in XcGrowth
    s = scenario_setup.create_soil_model(usemoles = usemoles, 
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 356, in create_soil_model
    s = setupOther(s, p_mean_)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../inputDataTillage/scenario_setup.py", line 407, in setupOther
    s.initializeProblem(s.maxDt)
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 321, in initializeProblem
    self.cellSurfacesCyl = self._map(self._flat0(comm.gather(self.base.getCellSurfacesCyl(),root=0)), 2) * 1.e4  # m2 -> cm2
  File "/mnt/beegfs-ssd/home/m.giraud/dumux38bis/dumux/dumux-rosi/experimental/fixedPointIter2/scripts/../modules/solverbase.py", line 648, in _map
    print('assert len(indices) == len(x)',
Exception
mpirun: Forwarding signal 18 to job
slurmstepd: error: *** JOB 30226 ON node14 CANCELLED AT 2024-08-08T18:53:57 ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 3401375 on node node14 exited on signal 15 (Terminated).
--------------------------------------------------------------------------
